### ISSUE TITLE
Error in marker.ts

### ISSUE THREAD

**Issue by Tobii42** [elasticrash/ngx.leaflet.component#111]
While building my project with angular2.leaflet.component, I get the following error:

```
ERROR in [my project directory]/node_modules/angular2.leaflet.components/marker/marker.ts (65,81): Argument of type '{ icon: Icon; options: null; }' is not assignable to parameter of type 'MarkerOptions'.
Object literal may only specify known properties, and 'options' does not exist in type 'MarkerOptions'.)
```

For me, I can resolve that issue by removing that options property in line 65 in marker.ts:
`model.marker = L.marker([model.lat, model.lon], { icon: myIcon });`

Nevertheless, I don't know if that is a correct fix or if it removes some capabilities of the marker. I wonder, if I'm the only one with this problem?

Thank you for the time you invest in this project!
Greetings,
Tobi

**Comment by elasticrash** [comment]
There is a similar open request for that particular problem. I do think it is something to do with the tsconfing setup though

**Comment by Tobii42** [comment]
Thank you for your response. If it's helpful for you, here's my tsconfig.json:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```

**Comment by alexispolak** [comment]
Same problem here, here it's my tsconfig.json

`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
`

**Comment by alexispolak** [comment]
Download the last version, with the last pull request added. The error still here:

`node_modules/angular2.leaflet.components/marker/marker.ts(65,81): error TS2345: Argument of type '{ icon: Icon; options: null; }' is not assignable to parameter of type 'MarkerOptions'.
  Object literal may only specify known properties, and 'options' does not exist in type 'MarkerOptions'.
typings/globals/node/index.d.ts(78,6): error TS2300: Duplicate identifier 'BufferEncoding'.
typings/globals/node/index.d.ts(234,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/globals/node/index.d.ts(518,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(519,9): error TS2502: 'SlowBuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(520,26): error TS2300: Duplicate identifier 'Buffer'.
typings/globals/node/index.d.ts(520,50): error TS2300: Duplicate identifier 'SlowBuffer'.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'addListener' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'emit' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'on' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'once' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'prependListener' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'prependOnceListener' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(703,18): error TS2300: Duplicate identifier 'Agent'.
typings/globals/node/index.d.ts(748,18): error TS2300: Duplicate identifier 'Worker'.
typings/globals/node/index.d.ts(1141,22): error TS2300: Duplicate identifier 'CompleterResult'.
typings/globals/node/index.d.ts(1181,18): error TS2300: Duplicate identifier 'Script'.
typings/globals/node/index.d.ts(1848,18): error TS2451: Cannot redeclare block-scoped variable 'constants'.
typings/globals/node/index.d.ts(2076,18): error TS2300: Duplicate identifier 'TLSSocket'.
typings/globals/node/index.d.ts(2308,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
typings/globals/node/index.d.ts(2309,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
typings/globals/node/index.d.ts(2310,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
typings/globals/node/index.d.ts(2311,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
typings/globals/node/index.d.ts(2312,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
typings/globals/node/index.d.ts(2449,22): error TS2420: Class 'Readable' incorrectly implements interface 'ReadableStream'.
  Types of property 'pause' are incompatible.
    Type '() => Readable' is not assignable to type '{ (): ReadableStream; (): ReadableStream; }'.
      Type 'Readable' is not assignable to type 'ReadableStream'.
        Property 'isPaused' is missing in type 'Readable'.
typings/globals/node/index.d.ts(2472,22): error TS2420: Class 'Writable' incorrectly implements interface 'WritableStream'.
  Types of property 'eventNames' are incompatible.
    Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
      Type '(string | symbol)[]' is not assignable to type 'string[]'.
        Type 'string | symbol' is not assignable to type 'string'.
          Type 'symbol' is not assignable to type 'string'.
typings/globals/node/index.d.ts(2490,22): error TS2420: Class 'Duplex' incorrectly implements interface 'ReadWriteStream'.
  Types of property 'pause' are incompatible.
    Type '() => Duplex' is not assignable to type '{ (): ReadWriteStream; (): ReadWriteStream; }'.
      Type 'Duplex' is not assignable to type 'ReadWriteStream'.
        Property 'isPaused' is missing in type 'Duplex'.
typings/globals/node/index.d.ts(2511,22): error TS2420: Class 'Transform' incorrectly implements interface 'ReadWriteStream'.
  Types of property 'pause' are incompatible.
    Type '() => Transform' is not assignable to type '{ (): ReadWriteStream; (): ReadWriteStream; }'.
      Type 'Transform' is not assignable to type 'ReadWriteStream'.
        Property 'isPaused' is missing in type 'Transform'.
typings/globals/node/index.d.ts(2536,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(2619,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(2641,18): error TS2300: Duplicate identifier 'Domain'.
typings/globals/node/index.d.ts(2641,18): error TS2420: Class 'Domain' incorrectly implements interface 'NodeJS.Domain'.
  Types of property 'eventNames' are incompatible.
    Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
      Type '(string | symbol)[]' is not assignable to type 'string[]'.
        Type 'string | symbol' is not assignable to type 'string'.
          Type 'symbol' is not assignable to type 'string'.
typings/globals/node/index.d.ts(2933,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(2959,5): error TS2300: Duplicate identifier 'export='.
../../../node_modules/@angular/common/src/pipes/async_pipe.d.ts(9,28): error TS2307: Cannot find module 'rxjs/Observable'.
../../../node_modules/@angular/core/src/application_ref.d.ts(8,28): error TS2307: Cannot find module 'rxjs/Observable'.
../../../node_modules/@angular/core/src/event_emitter.d.ts(8,25): error TS2307: Cannot find module 'rxjs/Subject'.
../../../node_modules/@angular/core/src/linker/query_list.d.ts(8,28): error TS2307: Cannot find module 'rxjs/Observable'.
../../../node_modules/@angular/core/src/util/lang.d.ts(8,28): error TS2307: Cannot find module 'rxjs/Observable'.
../../../node_modules/@types/node/index.d.ts(70,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'main' must be of type 'any', but here has type 'NodeModule'.
../../../node_modules/@types/node/index.d.ts(81,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'parent' must be of type 'any', but here has type 'NodeModule'.
../../../node_modules/@types/node/index.d.ts(82,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'children' must be of type 'any[]', but here has type 'NodeModule[]'.
../../../node_modules/@types/node/index.d.ts(102,6): error TS2300: Duplicate identifier 'BufferEncoding'.
../../../node_modules/@types/node/index.d.ts(256,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'errno' must be of type 'string', but here has type 'number'.
../../../node_modules/@types/node/index.d.ts(263,18): error TS2300: Duplicate identifier 'EventEmitter'.
../../../node_modules/@types/node/index.d.ts(411,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'platform' must be of type 'string', but here has type 'Platform'.
../../../node_modules/@types/node/index.d.ts(569,26): error TS2300: Duplicate identifier 'Buffer'.
../../../node_modules/@types/node/index.d.ts(569,50): error TS2300: Duplicate identifier 'SlowBuffer'.
../../../node_modules/@types/node/index.d.ts(593,22): error TS2415: Class 'EventEmitter' incorrectly extends base class 'internal'.
  Types of property 'eventNames' are incompatible.
    Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
      Type '(string | symbol)[]' is not assignable to type 'string[]'.
        Type 'string | symbol' is not assignable to type 'string'.
          Type 'symbol' is not assignable to type 'string'.
../../../node_modules/@types/node/index.d.ts(613,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
../../../node_modules/@types/node/index.d.ts(706,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'httpVersionMajor' must be of type 'string', but here has type 'number'.
../../../node_modules/@types/node/index.d.ts(707,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'httpVersionMinor' must be of type 'string', but here has type 'number'.
../../../node_modules/@types/node/index.d.ts(708,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'connection' must be of type 'any', but here has type 'Socket'.
../../../node_modules/@types/node/index.d.ts(758,18): error TS2300: Duplicate identifier 'Agent'.
../../../node_modules/@types/node/index.d.ts(813,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'addressType' must be of type 'string', but here has type 'number | "udp4" | "udp6"'.
../../../node_modules/@types/node/index.d.ts(816,18): error TS2300: Duplicate identifier 'Worker'.
../../../node_modules/@types/node/index.d.ts(1153,16): error TS2403: Subsequent variable declarations must have the same type.  Variable 'constants' must be of type '{ UV_UDP_REUSEADDR: number; errno: { SIGHUP: number; SIGINT: number; SIGQUIT: number; SIGILL: num...', but here has type '{ UV_UDP_REUSEADDR: number; signals: { SIGHUP: number; SIGINT: number; SIGQUIT: number; SIGILL: n...'.
../../../node_modules/@types/node/index.d.ts(1499,17): error TS2300: Duplicate identifier 'CompleterResult'.
../../../node_modules/@types/node/index.d.ts(1536,18): error TS2300: Duplicate identifier 'Script'.
../../../node_modules/@types/node/index.d.ts(2484,22): error TS2451: Cannot redeclare block-scoped variable 'constants'.
../../../node_modules/@types/node/index.d.ts(2832,18): error TS2300: Duplicate identifier 'TLSSocket'.
../../../node_modules/@types/node/index.d.ts(3206,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
../../../node_modules/@types/node/index.d.ts(3207,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
../../../node_modules/@types/node/index.d.ts(3208,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
../../../node_modules/@types/node/index.d.ts(3209,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
../../../node_modules/@types/node/index.d.ts(3210,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
../../../node_modules/@types/node/index.d.ts(3349,22): error TS2420: Class 'Readable' incorrectly implements interface 'ReadableStream'.
  Types of property 'pause' are incompatible.
    Type '() => Readable' is not assignable to type '{ (): ReadableStream; (): ReadableStream; }'.
      Type 'Readable' is not assignable to type 'ReadableStream'.
        Types of property 'eventNames' are incompatible.
          Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
            Type '(string | symbol)[]' is not assignable to type 'string[]'.
              Type 'string | symbol' is not assignable to type 'string'.
                Type 'symbol' is not assignable to type 'string'.
../../../node_modules/@types/node/index.d.ts(3432,22): error TS2420: Class 'Writable' incorrectly implements interface 'WritableStream'.
  Types of property 'eventNames' are incompatible.
    Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
      Type '(string | symbol)[]' is not assignable to type 'string[]'.
        Type 'string | symbol' is not assignable to type 'string'.
          Type 'symbol' is not assignable to type 'string'.
../../../node_modules/@types/node/index.d.ts(3516,22): error TS2420: Class 'Duplex' incorrectly implements interface 'ReadWriteStream'.
  Types of property 'pause' are incompatible.
    Type '() => Duplex' is not assignable to type '{ (): ReadWriteStream; (): ReadWriteStream; }'.
      Type 'Duplex' is not assignable to type 'ReadWriteStream'.
        Types of property 'eventNames' are incompatible.
          Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
            Type '(string | symbol)[]' is not assignable to type 'string[]'.
              Type 'string | symbol' is not assignable to type 'string'.
                Type 'symbol' is not assignable to type 'string'.
../../../node_modules/@types/node/index.d.ts(3537,22): error TS2420: Class 'Transform' incorrectly implements interface 'ReadWriteStream'.
  Types of property 'pause' are incompatible.
    Type '() => Transform' is not assignable to type '{ (): ReadWriteStream; (): ReadWriteStream; }'.
      Type 'Transform' is not assignable to type 'ReadWriteStream'.
        Types of property 'eventNames' are incompatible.
          Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
            Type '(string | symbol)[]' is not assignable to type 'string[]'.
              Type 'string | symbol' is not assignable to type 'string'.
                Type 'symbol' is not assignable to type 'string'.
../../../node_modules/@types/node/index.d.ts(3563,5): error TS2300: Duplicate identifier 'export='.
../../../node_modules/@types/node/index.d.ts(3646,5): error TS2300: Duplicate identifier 'export='.
../../../node_modules/@types/node/index.d.ts(3668,18): error TS2300: Duplicate identifier 'Domain'.
../../../node_modules/@types/node/index.d.ts(3668,18): error TS2420: Class 'Domain' incorrectly implements interface 'NodeJS.Domain'.
  Types of property 'eventNames' are incompatible.
    Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
      Type '(string | symbol)[]' is not assignable to type 'string[]'.
        Type 'string | symbol' is not assignable to type 'string'.
          Type 'symbol' is not assignable to type 'string'.
../../../node_modules/@types/node/index.d.ts(3960,5): error TS2300: Duplicate identifier 'export='.
../../../node_modules/@types/node/index.d.ts(4004,5): error TS2300: Duplicate identifier 'export='.
`

**Comment by elasticrash** [comment]
@alexispolak 
the library uses @types and not typings so certrain typings needs to be excluded anyway the following tsconfig works fine for me. So Ill close the issue for the time.


```{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "dist/Angular.io.MapViewer/app",
    "declaration": false,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "types": [
    "node",
    "jasmine",
    "core-js",
    "hammerjs",
    "leaflet"
  ]
}
