### ISSUE TITLE
Errors in files

### ISSUE THREAD

**Issue by AlexeyKorkoza** [elasticrash/ngx.leaflet.component#112]
Hello, Trying to use the Angular2.leaflet.component in my angular2 project, after following the readme file , I get these build errors.

`node_modules/angular2.leaflet.components/circle/circle.ts(55,9): error TS7005: Variable 'textInput' implicitly has an 'any' type.
node_modules/angular2.leaflet.components/circlemarker/circlemarker.ts(54,9): error TS7005: Variable 'textInput' implicitly has an 'any' type.
node_modules/angular2.leaflet.components/imageoverlay/image-overlay.ts(26,9): error TS7005: Variable 'layer' implicitly has an 'any' type.
node_modules/angular2.leaflet.components/layer/layer.ts(27,9): error TS7005: Variable 'layer' implicitly has an 'any' type.
node_modules/angular2.leaflet.components/map/map.ts(27,3): error TS7008: Member 'layerControlObject' implicitly has an 'any' type.
node_modules/angular2.leaflet.components/marker/marker.ts(50,50): error TS7006: Parameter 'exists' implicitly has an 'any' type.
node_modules/angular2.leaflet.components/marker/marker.ts(53,13): error TS7006: Parameter 'image' implicitly has an 'any' type.
node_modules/angular2.leaflet.components/marker/marker.ts(65,81): error TS2345: Argument of type '{ icon: Icon; options: null; }' is not assignable to parameter of type 'MarkerOptions
'.
  Object literal may only specify known properties, and 'options' does not exist in type 'MarkerOptions'.
.......`

Link to my project: 
https://github.com/AlexeyKorkoza/Angular-2-leaflet-starter

Any ideas?  

Thank you very match!

**Comment by elasticrash** [comment]
its your typescript compiler configuration, you are too strict, I do use ```any``` because leaflet @types do not always work as expected

change the ```noImplicitAny```

**Comment by AlexeyKorkoza** [comment]
It's great! Most of the errors have disappeared, but now I have two errors:
1.`node_modules/angular2.leaflet.components/marker/marker.ts(65,81): error TS2345: Argument of type '{ icon: Icon; options: null; }' is not assignable to parameter of type 'MarkerOptions'.
2. Object literal may only specify known properties, and 'options' does not exist in type 'MarkerOptions'.
node_modules/angular2.leaflet.components/marker/marker.ts(114,8): error TS2339: Property 'map' does not exist on type 'Observable<Response>'.
`
About first error saying in this issue: https://github.com/elasticrash/Angular2.leaflet.component/issues/111

How to fix second error ?

**Comment by elasticrash** [comment]
again its a config thing, but I am trying to fix those. There is a relevant pull request that i need to review. I wish I could replicate them to be honest, so Ill use your config to see If Ill get them myself. My tsconfig usually looks like this

https://github.com/elasticrash/Angular.io.MapViewer/blob/developing_npm_module/tsconfig.json

**Comment by AlexeyKorkoza** [comment]
It's ok. I'll wait for a response from you

**Comment by elasticrash** [comment]
I am not getting any problems with the following config at the time.
https://github.com/elasticrash/Angular.io.MapViewer/blob/developing_npm_module/tsconfig.json
