### ISSUE TITLE
Angular 4 Support

### ISSUE THREAD

**Issue by alexispolak** [elasticrash/ngx.leaflet.component#117]
Hi ! Can't make it work in Angular 4, i can not find the SystemJS file in the project structure, so i can not follow the wiki tutorial. Are you going to support future releases of angular ? Thanks

**Comment by elasticrash** [comment]
I am already using angular 4 on the develop-1.4 branch with no issues.
I have a test app here using SystemJs https://github.com/elasticrash/Angular.io.MapViewer/tree/developing_npm_module

But SystemJs shouldn't require any changes.

In case you are using Webpack and AngularCli you don't really need to do anything other than installing it. Maybe I should create an example project for those as well.

**Comment by alexispolak** [comment]
I'm using AngularCli, i would be really useful an example project. Thanks a lot !

**Comment by landesko** [comment]
Looking for AngularCLI support as well!

**Comment by elasticrash** [comment]
I really didn't have to do much except pasting the example source code (with a couple of minor changes) (no code changes for the actual library)

working example for angular4/@angular-cli
https://github.com/elasticrash/Angular.io.MapViewer/tree/angular-cli-example
